services:
  myno:
    image: sunnyramagiri/myno:latest
    ports:
      - "9090:8080"
    depends_on:
      - myhttp

  myhttp:
    image: tomee
    ports:
      - 7070:8080
    networks:
      - mywebserver

networks:
  mywebserver:
    driver: bridge
