---
services:
  mywebserver:
    image: tomee
    ports:
      - 9090:8080
    networks:
      - mywebserver
    
   
  myhttp:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sun
      MYSQL_DATABASE: mydb      
      MYSQL_USER: sun            
      MYSQL_PASSWORD: sun123
    networks:
      - mywebserver

networks:
  mywebserver:
    driver: bridge
